Time::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:date] = '%Y/%m/%d'
Time::DATE_FORMATS[:date_dot] = '%Y.%m.%d'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Time::DATE_FORMATS[:month] = '%-m月%-d日 %H:%M'
Time::DATE_FORMATS[:date_jp] = '%Y年%m月%d日'
Date::DATE_FORMATS[:date_jp] = '%Y年%m月%d日'
